### ISSUE TITLE
有关贡献代码的更详细的说明

### ISSUE THREAD

**Issue by LittleYe233** [MakinoharaShoko/WebGAL#117]
# 问题描述

[DEV_NOTE.md](https://github.com/MakinoharaShoko/WebGAL/blob/main/DEV_NOTE.md) 中对于开发计划的描述如下：

> | bug fix | new feature                            |
> | ------- | -------------------------------------- |
> |         | 支持更多全局特效（红视、闪烁、眨眼等） |
> |         | 脚本支持函数                           |
> |         | （提案）引入WebGL 3D 演出              |
> |         | 加入音量控制                           |
> |         | 设法使得UI可定制化                     |

部分计划缺乏必要的标准（例如，脚本新语法的格式），可能对其他贡献者贡献代码造成影响。

**Comment by MakinoharaShoko** [comment]
好的，我近期完善文档

**Comment by MakinoharaShoko** [comment]
#120
