### ISSUE TITLE
游戏脚本文件的扩展名对语法高亮有影响

### ISSUE THREAD

**Issue by LittleYe233** [MakinoharaShoko/WebGAL#118]
# 问题描述

对于 VS Code 或 Sublime Text 等文本编辑器用户，若要对游戏脚本文件进行语法高亮，一般需要对文件的扩展名进行限定，避免对其他扩展名的文件的语法高亮造成影响。而目前其扩展名为 `.txt`，会与 Plain Text 格式支持的扩展名相冲突。故建议更改游戏脚本文件的扩展名。

# 原因

1. 对与部分文本编辑器内建的语法高亮产生冲突；
2. 项目开发者和用户均可以快速作出更改，而不需要大面积重构。

**Comment by MakinoharaShoko** [comment]
其实第一版的剧本格式是 `.sce` ，但是由于本引擎的目标群体是可能没有任何经验的制作者，我担心他们不会修改拓展名，所以使用了 `.txt` 作为拓展名。
其实本引擎可以使用任何拓展名格式。除了 `start.txt` 必须是txt格式外，在 `changeScene` `choose` 命令中指定的新剧本文件皆可以使用自由的拓展名。
