### ISSUE TITLE
`npm run build` 报 'error:03000086:digital envelope routines::initialization error' 错误

### ISSUE THREAD

**Issue by LittleYe233** [MakinoharaShoko/WebGAL#119]
# 问题描述

Node.js 17.x 版本运行 `npm run build` 或 `yarn run build` 时会报 'error:03000086:digital envelope routines::initialization error' 错误。

# 解决方法

参考链接 [Node.js 17.0.1 Gatsby error - "digital envelope routines::unsupported ... ERR_OSSL_EVP_UNSUPPORTED"](https://stackoverflow.com/a/69746387/12002560)。需要在 `package.json` 的 `"scripts"` 字段作如下修改：

```json
"build": "react-scripts --openssl-legacy-provider build"
```

之后再执行 `npm run build`。

**Comment by MakinoharaShoko** [comment]
好的，我很快会在文档里加上相关说明

**Comment by MakinoharaShoko** [comment]
#120
