### ISSUE TITLE
关于播放动画时的问题

### ISSUE THREAD

**Issue by bcqsd** [MakinoharaShoko/WebGAL#178]
demo里面的重播和自动点击都没有反应
播放动画的时候无论点击什么按钮动画都在继续播放，bgm也在响。点击返回标题之后也有bgm，感觉不太合适诶。

**Comment by MakinoharaShoko** [comment]
“重播”指的是重播语音。
“自动”指的是自动播放，我刚刚试了一下，功能是正常的。
回标题后会播放标题bgm。
> 播放动画的时候无论点击什么按钮动画都在继续播放
有些动画是不可打断演出，请参考 https://github.com/MakinoharaShoko/WebGAL/blob/main/src/Core/controller/%E6%BC%94%E5%87%BA%E8%B0%83%E7%94%A8%E8%AF%B4%E6%98%8E.md

**Comment by bcqsd** [comment]
> 

我刚刚试了一下，在观看特效的选项之前点击快进，然后动画会被快进跳过，但是动画的bgm却触发了，之后返回标题播放的也是动画的bgm（demo里面动画bgm和标题bgm是一样的，不过并没有重新播放），然后无论进行读档和其他操作，bgm都在继续播放
甚至重新开始游戏进入动画那个场景，可以分辨出有两个bgm在响
这个问题似乎是快进功能引起的。我不知道故障的bgm是标题bgm还是动画bgm引起的，如果可以最好设置两个不同的bgm

正常情况回标题，没有bgm（demo里面只有一个bgm，具体的逻辑我还没看怎么写的）
如果在播放动画的时候回标题，会继续播放动画的bgm，但是点击进入游戏或读档bgm会消失
如果在特效选项之前快进（或者在选项出现的时候点击快进然后点选项），**有几率**动画会被跳过，bgm会不可打断地播放

我重复试了好多遍，首先回标题之后再重新开游戏，快进功能上面是显示正在快进的样子，其实没有快进。这是我之前说快进功能错误的原因，其实需要再点一次。

然后那个动画跳过bgm播放的bug，不是每一次都能复现，我没找到一定能让这个bug出现的方法。就不停快进->选项->如果没有bgm顺利来到蛋包饭选项，就返回标题->开始游戏，快进->... 过个三五次就会出现。（在我有意识统计的情况下最多重复5次会出现）

**Comment by MakinoharaShoko** [comment]
好的，我近期会着手修复

**Comment by MakinoharaShoko** [comment]
#183
