### ISSUE TITLE
Feature request 剧本的格式

### ISSUE THREAD

**Issue by wanghaisheng** [MakinoharaShoko/WebGAL#185]
有无可能适配 
https://fountain.advjs.org/guide/

目前的图形化非常棒，但一些基础的配置加载工作其实可以靠剧本自动化的导入，类似导入一个剧本模板，模板的定义我猜测目前使用咱们自定义的格式，为了降低上手成本，进一步丰富生态，标准化的格式其实是一个更好的选择

我有意愿参与这部分工作

1.做一个fountain 2 现有剧本的转换

**Comment by MakinoharaShoko** [comment]
近期我正打算为编辑器添加更多脚本编辑功能，现有的编辑器内部脚本描述在。待编辑器可以编辑的脚本类型进一步完善后，我很欢迎你能够参与到 WebGAL 编辑器的建设中来！

https://github.com/MakinoharaShoko/WebGAL_Origine/blob/main/src/components/editor/components/editorMain/sceneEditor/createSentence.js

如果你有兴趣，可以先阅读一下相关信息。

不过目前我还没有为之设计一个明确的规范，我近期会考虑开始制定相关规范，感谢你的建议！

**Comment by wanghaisheng** [comment]
没事我先玩一下  

我魔改过一个https://github.com/LuisMayo/objection_engine 简单的立绘放置 tts的背景配音 背景插图片 插视频 但我发现 再往前走 要进阶的话 特效 动画 就有点难住我了


然后还调研了一些常见的visual novel的engine

   Ren'Py：如果你没有编程基础但是想学，或者有Python基础，推荐用这个引擎

   AVG.js：如果你信仰web前端，推荐用这个引擎

   Librian：Python后端和web前端混合的引擎，作者是个萝莉控

   AVGPlus：另一个使用web前端的引擎，似乎得到了Xihe Animation的支持

   Snowing：用C++写的硬核引擎

 

以及通用游戏引擎：

 

   PainterEngine：由C语言编写的跨平台图形应用框架

   EtherEngine：基于Lua的跨平台游戏接口

   Luna Engine：这个引擎不是我们做的，不过看起来很有意思

   UniGal：为了解决各家视觉小说引擎的碎片化问题，而定义的通用脚本格式

https://github.com/Monogatari/Monogatari
