### ISSUE TITLE
关于intro使用

### ISSUE THREAD

**Issue by TheNewMillium2nd** [MakinoharaShoko/WebGAL#186]
（可恶的B站私信限制...Github号绑定的邮箱密码又丢没看见了只好现注册一个新号...）

感谢先生制作了如此简单易用的Galgame工具，赞美！
主要是问个问题...
intro“独白”部分在使用时候，是默认不需要鼠标操控，直接自动播放的。
能不能在之后的更新中，加入鼠标点击一次换一行的功能，或者独白部分可选择不是整段整段出现而是与正常对话类似的文字显示机制呢？
对于我这种从型月入坑的Galgame玩家，如果真的能用上这种方法，那真的感激不尽（倒

**Comment by MakinoharaShoko** [comment]
你的意见已收到。
