### ISSUE TITLE
问两个关于视频的问题

### ISSUE THREAD

**Issue by wanghaisheng** [MakinoharaShoko/WebGAL#189]
1.引入视频播放，怎么刷特殊字幕在视频上面 同时播放语音看到已经有了
2.大多数游戏都有一些新手引导类的，我们的这个有没有可能集成intro.js这种

**Comment by MakinoharaShoko** [comment]
有可能，但是可能需要制作者自行改造代码并构建。一般来说来说，前端开发者可以很轻松地为这个引擎扩充功能。

**Comment by MakinoharaShoko** [comment]
关于第一点，其实也可以通过引入新的自定义演出实现，但是需要一定的前端开发基础。我提供的功能只是一些基础的功能，更多功能的实现需要我慢慢补充。

**Comment by wanghaisheng** [comment]
我去试试看
