### ISSUE TITLE
Safari游玩中出现剧情文本显示异常

### ISSUE THREAD

**Issue by TheNewMillium** [MakinoharaShoko/WebGAL#194]
我朋友使用Safari游玩制作的游戏时出现了剧情文字不会自动换行的问题。
之后我使用iPhone6（iOS 12）上的Safari游玩时，也发现了同样的问题。
关于这个，作者先生遇到过类似的情况吗？
如果有，之后的版本更新中会对其进行专门修正吗？

**Comment by MakinoharaShoko** [comment]
由于我缺乏苹果设备，所以没有测试过 Safari 的情况。你可以将具体表现截图发在下面。

**Comment by TheNewMillium** [comment]
![43c9c6acbeebc185](https://user-images.githubusercontent.com/52703228/178151572-83b3c7fb-6b53-4193-8392-d7916b37107c.jpg)
![53f38326c825f584](https://user-images.githubusercontent.com/52703228/178151576-fc4d32ad-9584-43ce-aa07-59c4b9ee7fd5.jpg)
![-67e36a5d819165d7](https://user-images.githubusercontent.com/52703228/178151595-b7182713-d674-48e6-97a6-459b1949ea3f.png)
刚找了群友测试一下readme的开发完成游戏。
1、2分别为iPad、iPhone测试结果，均为异常。
3是某群友凑热闹拿Windows测的结果，正常。

**Comment by MakinoharaShoko** [comment]
好的，我近期排查一下情况

**Comment by MakinoharaShoko** [comment]
http://dongshangchen.com/2014/11/23/safari%E6%96%87%E6%9C%AC%E4%B8%8D%E8%83%BD%E6%8D%A2%E8%A1%8C%E7%9A%84%E5%B0%8Fbug/

**Comment by MakinoharaShoko** [comment]
此问题是 Safari 浏览器无法识别字体导致的 bug，现在正在寻找方案修复。

**Comment by mikezzb** [comment]
感觉是Safari没有正常识别CJK，把中文整句认作了一个单词？
在Safari中试了word-break: break-word，可以把中文像长单词一样换行。

**Comment by mikezzb** [comment]
<img width="1680" alt="Screenshot 2022-09-02 at 2 04 18 AM" src="https://user-images.githubusercontent.com/23418428/187985973-62b59303-4c14-4209-9296-963677b71e5c.png">
