### ISSUE TITLE
怎样才能让源代码跑起来呢？

### ISSUE THREAD

**Issue by skyejy** [MakinoharaShoko/WebGAL#197]
WebGAL/src/Components/UI/Menu/MenuPanel/MenuPanel.tsx 
你好，我们更改了源代码这个文件的内容，请问：更改后，怎样才能让源代码跑起来呢？
![image](https://user-images.githubusercontent.com/26304541/182511502-6774417a-715e-4d86-98b2-c895c44b1d56.png)
请问开发指引文档里的这段描述具体应该怎么做呢？

**Comment by MakinoharaShoko** [comment]
你需要为你的计算机安装 Node.js ，然后使用终端工具（如 Git Bash、Powershell等）进入源代码的**根目录**，输入以上指令即可进行构建。如果你希望实时预览效果，请使用 npm run start 来预览。

**Comment by skyejy** [comment]
好的 非常感谢！
