### ISSUE TITLE
关于脚本文件的编辑

### ISSUE THREAD

**Issue by WakingInsect** [MakinoharaShoko/WebGAL#2]
1. 在编写剧本文件时，如果使用中文的角色名和中文对白，需要多次切换输入法：

**角色名** 切换英文输入法  **：** 切换中文输入法 **对白内容** 切换英文输入法 **;** 切换中文输入法

即便是省略分号，也需要两次切换，这样写未免太繁琐。

而且在同一个角色有连续对话的时候，会重复输入角色名。

我认为可以试着像yml那样，依靠缩进来区分角色和对白，通过换行来结束语句。强制换行另说。

2. 在读取图片资源时，如果资源未找到，原因可能有很多，如格式不正确，文件名写错等。在运行时会在上方出现默认的缺省图标，可以尝试在控制台打印异常信息。

**Comment by MakinoharaShoko** [comment]
你的意见已收到，有关重复输入角色名的问题将在下个版本改进。但是为了保证语言的简单性，暂不考虑使用缩进代替语句（因为我的引擎是面向几乎毫无编程水平的初学者，他们可能无法很好地理解缩进）。

**Comment by MakinoharaShoko** [comment]
图片资源加载失败后导致的显示问题目前也正在尝试修复中。

**Comment by MakinoharaShoko** [comment]
![image](https://user-images.githubusercontent.com/30483415/135957632-a6d6ad0e-21d4-4db3-b4a0-659f690249fe.png)
在下个版本中，如果你使用这样的语句，就可以在不改变人物名称的情况下连续输出对话。
