### ISSUE TITLE
4.x 代码pull下来没有src 文件夹

### ISSUE THREAD

**Issue by zhaocaimin** [MakinoharaShoko/WebGAL#209]
最新版本main pull 下来 没有src文件夹，老哥有群没有加群交流一下

**Comment by MakinoharaShoko** [comment]
现在使用 monorepo 管理，代码在packages 目录下

**Comment by zhaocaimin** [comment]
不对我的描述有问题
 应该是
 [在本地通过书写脚本的形式开发，并实时调试]( https://docs.msfasr.com/guide/#%E6%96%B9%E6%B3%952-%E5%9C%A8%E6%9C%AC%E5%9C%B0%E9%80%9A%E8%BF%87%E4%B9%A6%E5%86%99%E8%84%9A%E6%9C%AC%E7%9A%84%E5%BD%A2%E5%BC%8F%E5%BC%80%E5%8F%91-%E5%B9%B6%E5%AE%9E%E6%97%B6%E8%B0%83%E8%AF%95)
 这个·里面的版本 vite 所 build的index.html 里面的 src/main.ts 没有。 直接没有 src文件夹

**Comment by MakinoharaShoko** [comment]
打包过的肯定是没有源代码的
