### ISSUE TITLE
能否添加改变bgm和语音的音量功能

### ISSUE THREAD

**Issue by RyzenLing** [MakinoharaShoko/WebGAL#221]
例如bgm:test.mp3 -vol=1;
这样就能很好的把握音量了

**Comment by MakinoharaShoko** [comment]
你的建议已收到

**Comment by labiker** [comment]
BGM的音量调整功能已实装。
语音的音量调整功能正在实装中，请稍等。
The BGM volume adjustment function has been implemented.
The voice volume adjustment function is being implemented, please wait.

拉取请求/pull request: https://github.com/MakinoharaShoko/WebGAL/pull/322

**Comment by labiker** [comment]
Vocal的音量调整功能已实装。
The vocal volume adjustment function has been implemented.

拉取请求/pull request: https://github.com/MakinoharaShoko/WebGAL/pull/324
