### ISSUE TITLE
背景支持GIF

### ISSUE THREAD

**Issue by MakinoharaShoko** [MakinoharaShoko/WebGAL#245]

**Comment by MakinoharaShoko** [comment]
It seems that simply importing a library can achieve this functionality? It appears that GIF loading uses the same set of methods as loading other resources

**Comment by generalfreed** [comment]
@MakinoharaShoko 
As I am planning to integrate @pixi/gif version 2.1.0 into the project, it has come to my attention that this new dependency requires an update to @pixi/core. Specifically, @pixi/gif 2.1.0 has a peer dependency on @pixi/assets version 7.0.0 or higher, which in turn requires @pixi/core version 7.2.4.

I attempted to update @pixi/core using the --legacy-peer-deps flag to bypass the npm ERESOLVE errors. However, updating to @pixi/core 7.2.4 causes type mismatches in certain parts of the codebase, resulting in TypeScript compilation errors.

**Comment by MakinoharaShoko** [comment]
There may be some incompatibilities with the previous code after upgrading the dependencies. If they cannot be resolved, you can try other methods to manually support GIFs. Of course, if it is possible to directly use a library, that would be even better

**Comment by MakinoharaShoko** [comment]
The significance of supporting GIF as a background may not be significant. GIF is an outdated format, unfriendly to GPUs, and has very limited color depth.
Video will be supported as a background instead of GIF. Please refer to #248
