### ISSUE TITLE
添加UI效果音

### ISSUE THREAD

**Issue by MakinoharaShoko** [MakinoharaShoko/WebGAL#281]

**Comment by labiker** [comment]
拉取请求/pull request: https://github.com/MakinoharaShoko/WebGAL/pull/328

目前音效已能正常播放，但是 webgal-serviceworker.js 会出现莫名的报错。
![image](https://github.com/MakinoharaShoko/WebGAL/assets/49630998/66cbae5e-1ab8-4cb2-b81f-656e392cec11)

**Comment by labiker** [comment]
Fixed the problem that 'webgal-serviceworker.js' would report an error.

拉取请求/pull request: https://github.com/MakinoharaShoko/WebGAL/pull/328
