### ISSUE TITLE
Added newline processing in textbox

### ISSUE THREAD

**Issue by labiker** [MakinoharaShoko/WebGAL#315]
Added newline processing in textbox.
在文本框中添加换行处理。
改行機能の実装です。

This is the pull request for WebGAL. ↓
https://github.com/MakinoharaShoko/WebGAL/pull/314

This is the pull request for WebGAL Terre. ↓
https://github.com/MakinoharaShoko/WebGAL_Terre/pull/104

The effect is shown below. ↓
![image](https://github.com/MakinoharaShoko/WebGAL/assets/49630998/afdb4dbf-1d70-4429-abed-d3d0bca19ec3)

**Comment by generalfreed** [comment]
@MakinoharaShoko 

■ Functions to be added in the future
Currently you can change the font size on the engine side,
I would like to be able to arbitrarily change the font size of individual texts on the Terra side.
In many visual novel game performance, large letters are displayed when the voice is loud, and small letters are displayed when the voice is low.
(It may not be recommended to change the font size on the engine side, but please give me your opinion)

**Comment by MakinoharaShoko** [comment]
This is a great feature that can be considered to allow temporary override of text size through scripts

**Comment by generalfreed** [comment]
thank you.
I'll it try.

**Comment by IdrilK** [comment]
(I'm directly changing the default size in the CSS :D) so great. Don't forget to let the text box automatically adjust its height with a lot of text, and be careful not to overlap with the bottom menu ;).

**Comment by MakinoharaShoko** [comment]
Merged #314
