### ISSUE TITLE
Add an "Exit" button to the title screen

### ISSUE THREAD

**Issue by labiker** [MakinoharaShoko/WebGAL#316]
在标题画面添加”退出“按钮，点击该按钮后，会先弹出确认窗口，确认后方可退出游戏。
タイトルに「終了」ボタンを追加します。それをクリックすると、ゲームを終了する前に確認ダイアログが表示されます。
Add an "Exit" button to the title screen, and when you click it, a confirmation window will be displayed before you can exit the game.

The effect is shown below. ↓
![](https://cdn.discordapp.com/attachments/1130155373890904115/1135940628551839764/image.png)
![](https://cdn.discordapp.com/attachments/1130155373890904115/1135939273233805473/image.png)

**Comment by MakinoharaShoko** [comment]
There used to be an exit button in several previous versions. However, later on, considering that it is a web-based game and the exit button often couldn't function due to browser security policies, it was removed

**Comment by labiker** [comment]
Got it. This issue will be closed.
