### ISSUE TITLE
localStorage 存储问题

### ISSUE THREAD

**Issue by moyui** [MakinoharaShoko/WebGAL#32]
localStorage是有大小限制的，而且网页端应该是同一个域名吧，多gal就要共用一个storage了。
此外在未来肯定会遇到pc端和移动端的同步问题，这个地方需要再斟酌一下。

还有看了下项目架构，其实可以使用react官方提供的create-react-app脚手架，打包配置和环境配置就不需要自己配了。

如果是一个前端的练手项目的话挺好的，继续迭代吧

**Comment by MakinoharaShoko** [comment]
可以让开发者选择通过何种方式加载存档，localstorage只是一个默认的方式。如果开发者有能力写后端，那么这个问题应该不难解决。
同时，可以考虑不同的gal使用不同的key，这个key可以在config里面（以后会加）自定义
再及：不使用create-react-app是为了简化使用成本。

**Comment by moyui** [comment]
> 可以让开发者选择通过何种方式加载存档，localstorage只是一个默认的方式。如果开发者有能力写后端，那么这个问题应该不难解决。 同时，可以考虑不同的gal使用不同的key，这个key可以在config里面（以后会加）自定义 再及：不使用create-react-app是为了简化使用成本。

应该将开发和打包后的代码分离，发行应该使用打包后的代码，作者/contributor使用源码开发，所以create-react-app 是简化开发者的成本

**Comment by lixiang810** [comment]
localStorage 不够用的话用 IndexedDB 不就好了，那玩意儿能存 1G 还是 2G 来着。

**Comment by MakinoharaShoko** [comment]
> localStorage 不够用的话用 IndexedDB 不就好了，那玩意儿能存 1G 还是 2G 来着。

现在我加了压缩，感觉又够用了
