### ISSUE TITLE
Use statements to customize the UI

### ISSUE THREAD

**Issue by labiker** [MakinoharaShoko/WebGAL#336]
使用语句来定制UI。
这里考虑的，是除去现有的系统UI外，游戏开发者也许想要针对游戏内容特色追加的新UI。
例如，在游戏《变态监狱》中，游戏开发者们设计了一组图片选项，供玩家点击选择后进入不同路线。

Use statements to customize the UI.
The consideration here is that in addition to the existing system UI, game developers may want to add new UI for game content features.
For example, in the game "Hentai Proson", game developers have designed a set of image options for players to click to select and enter different routes.

ステートメントを使用して UI をカスタマイズします。
ここで考えているのは、既存のシステム UI に加えて、ゲーム開発者がゲーム コンテンツ機能用の新しい UI を追加する場合があることです。たとえば、ゲーム『ヘンタイ・プリズン』では、ゲーム開発者は、プレイヤーがクリックしてさまざまなルートを選択してエントリーできる一連の画像オプションを設計しました。
![image](https://github.com/MakinoharaShoko/WebGAL/assets/49630998/ccc988b1-6485-4d42-b9b7-988e3fcdb0ae)
![image](https://github.com/MakinoharaShoko/WebGAL/assets/49630998/6004e192-4442-4392-991d-a5ee3fa958f3)

我计划使用以下这组语句来复现上述效果。
I plan to use this set of statements to reproduce the above effect.
この一連のステートメントを使用して、上記の効果を再現する予定です。

```
; // Common.txt
ui:clickEvent_route_CHISATO.txt -normal=route_CHISATO.png -over=route_CHISATO_over.png -enterse=se_01.mp3 -clickse=voice_CHISATO_02.mp3;
ui:clickEvent_route_NOAH_KUREBAYASHI.txt -normal=route_NOAH_KUREBAYASHI.png -over=route_NOAH_KUREBAYASHI_over.png -enterse=se_01.mp3 -clickse=voice_NOAH_KUREBAYASHI_02.mp3;
ui:clickEvent_route_TAEKA_HATAE.txt -normal=route_TAEKA_HATAE.png -over=route_TAEKA_HATAE_over.png -enterse=se_01.mp3 -clickse=voice_TAEKA_HATAE_02.mp3;
ui:clickEvent_route_GRAND.txt -normal=route_GRAND.png -over=route_GRAND_over.png -enterse=se_01.mp3 -clickse=voice_GRAND_02.mp3;
pause; // Pause parsing

; // clickEvent_route_CHISATO.txt
...
; // clickEvent_route_NOAH_KUREBAYASHI.txt
...
; // clickEvent_route_TAEKA_HATAE.txt
...
; // clickEvent_route_GRAND.txt
...
```

::: note note
您将可以结合 `setAnimation` 来定制UI的展示效果。
`-normal`, `-over`, `-enterse` 和 `-clickse` 将会是可选参数。
省略 `-normal` 时，将会使用系统自带的默认UI。
省略 `-over` 时，将会参照 `-normal` 参数。
省略 `-enterse` 和 `-clickse` 时，将会播放系统自带的默认音效。

You will be able to combine `setAnimation` to customize the presentation of your UI.
`-normal`, `-over`, `-enterse` and `-clickse` will be optional parameters.
When `-normal` is omitted, the system's default UI will be used.
When `-over` is omitted, the `-normal` parameter will be referenced.
When `-enterse` and `-clickse` are omitted, the system's default sound effect will be played.

`-setAnimation` を利用して、UI のプレゼンテーションをカスタマイズできます。
`-normal`、`-over`、`-enterse` および `-clickse` はオプションのパラメータになります。
`-normal` を省略すると、システムのデフォルトの UI が使用されます。
`-over` を省略すると、`-normal` パラメータが参照されます。
`-enterse` と `-clickse` を省略すると、システムのデフォルトの効果音が再生されます。
:::

**Comment by IdrilK** [comment]
good idea!!! (or for textbook ;))
<img width="1440" alt="Capture d’écran 2023-08-11 à 02 05 59" src="https://github.com/MakinoharaShoko/WebGAL/assets/103700780/25d38194-be6d-44e7-ba92-0ec3b7ded6a6">

**Comment by labiker** [comment]
@IdrilK 
Making a vertical text box is quite difficult, and this command alone may not be possible.
In addition, the UI currently displayed by this command is displayed on the Pixijs stage, and the Pixijs hierarchy is below the dialog, which does not allow the UI to be displayed above the dialog.

**Comment by labiker** [comment]
@IdrilK 
Making a vertical text box is quite difficult, and this command alone may not be possible.
In addition, the UI currently displayed by this command is displayed on the Pixijs stage, and the Pixijs hierarchy is below the dialog, which does not allow the UI to be displayed above the dialog.

**Comment by IdrilK** [comment]
@labiker 
> Making a vertical text box is quite difficult, and this command alone may not be possible.
> In addition, the UI currently displayed by this command is displayed on the Pixijs stage, and the Pixijs hierarchy is below the dialog, which does not allow the UI to be displayed above the dialog.

so the old textbox is better ^_~
<img width="1437" alt="Capture d’écran 2023-08-13 à 21 28 18" src="https://github.com/MakinoharaShoko/WebGAL/assets/103700780/b484f225-0872-4065-8503-044446e0d839">

**Comment by MakinoharaShoko** [comment]
Currently, we have not yet started preparing the UI customization feature. In the future, we may pre-set several styles and then allow users to choose through a configuration file.
Currently, this task has not begun because we need to address the more complex issue of configuration file parsing beforehand. Otherwise, UI customization will be impossible to tackle

**Comment by IdrilK** [comment]
> Currently, we have not yet started preparing the UI customization feature. In the future, we may pre-set several styles and then allow users to choose through a configuration file.
> Currently, this task has not begun because we need to address the more complex issue of configuration file parsing beforehand. Otherwise, UI customization will be impossible to tackle
👍 
@MakinoharaShoko 
(later, no problem. there are priorities ^_^)

in the file config for (all textbox ) AND with a line for only one change :
blablabla -ChangeTextbox:MyMessage1.css;
or blablabla -VertcalTextbox -VerticalText (more simple, more like webgal)

I know I'm insisting (*Whistles*),
Vertical buttons are really an excellent idea and culturally associated with many Japanese visual novels.
Just like culturally many Japanese/Chinese visual novels use the vertical format for text boxes and/or text, occasionally.
I believe this possibility of using a vertical text area (and the possibility of using vertical text or not), is a really interesting choice for Webgal users at long term (later, later).

(Personally, I've abandoned the idea of using vertical textbox. It was just an idea and testing for others users )

_______________
Me:Sorry;
:Quietly exits this discussion;
;Ah, the French folks 🙄 
🤐
