### ISSUE TITLE
 error css ? (display in French)

### ISSUE THREAD

**Issue by IdrilK** [MakinoharaShoko/WebGAL#337]
<img width="1440" alt="Capture d’écran 2023-08-12 à 16 22 37" src="https://github.com/MakinoharaShoko/WebGAL/assets/103700780/d0d5dd8b-ac4d-4b66-ab94-f4472d899729">

- macOS, safari
- Webgal terre 4.4.2 (4.4.2 release "this night" and not the 4.4.2 official last month version. LMAO ;))

**Comment by MakinoharaShoko** [comment]
The issue has been acknowledged and we will proceed with the necessary repairs
