### ISSUE TITLE
About linking characters and dialogue

### ISSUE THREAD

**Issue by generalfreed** [MakinoharaShoko/WebGAL#338]
The character's dialogue is not tied to the character's ID, and it is not possible to internally determine which character is speaking.

if you can do the above
・The active talking character can be placed in the front, and the other characters can be placed in the back.
・It is possible to make the character that is actively talking brighter and the other characters darker.
・ Lip-sync the character who is actively talking, and do nothing for the other characters

Example script1:
changeFigure:xxx.png -id=A;
changeFigure:xxx.png -id=B;
good morning! -id=A;
Hello! -id=B;

Example script2:
changeFigure:xxx.png -left;
changeFigure:xxx.png -right;
good morning! -left;
Hello! -right;

Example script3(ID takes precedence):
changeFigure:xxx.png -left -id=A;
changeFigure:xxx.png -right -id=B;
good morning! -left -id=A;;
Hello! -right -id=B;

Image after function addition:
![image](https://github.com/MakinoharaShoko/WebGAL/assets/71590526/29278680-81e5-46d0-93f1-ddd95633d9b3)

**Comment by MakinoharaShoko** [comment]
The naming here can easily lead to misunderstandings. It should be changed to something like "Associated Illustration Position" and "Associated Illustration ID". Additionally, similar to how other editing components are handled, the selection of position and the filling of ID should be mutually exclusive. Only one of them can be filled in

**Comment by generalfreed** [comment]
@MakinoharaShoko 
・Confirmation of specifications
Associated Illustration Position = 立绘插图的位置
Associated Illustration ID = 立绘插图的ID
![select-1](https://github.com/MakinoharaShoko/WebGAL/assets/71590526/41ffabf3-e0c0-48bc-b968-4b19367a87ce)

·script
Since the script will be able to specify the position and ID,
There is such a pattern, but in this case it is assumed that the ID is given priority.

good morning! -left -id=A;

Wouldn't it be better to use -figureId instead of -id ?

**Comment by MakinoharaShoko** [comment]
Yeah

**Comment by generalfreed** [comment]
I will fix it 😊
Thank you.

**Comment by generalfreed** [comment]
Done.
Completed.
