### ISSUE TITLE
About unlockCg and unlockBgm

### ISSUE THREAD

**Issue by generalfreed** [MakinoharaShoko/WebGAL#341]
■ Current function
In WebGAL, when adding to Extra CG and Extra BGM, it is necessary to add the following script.
unlockCg:bg.png -name=TEST_CG;
unlockBgm:s_Title.mp3 -name=TEST_BGM;

■ Function proposal
If there is a name in the script below, automatically adding it to Extra CG and Extra BGM.
(if there is an element with the same name, do not add, if there is no name, do not add.)
This saves the trouble of writing scripts.

changeBg:bg.png -unlockname=TEST_CG;
bgm:s_Title.mp3 -unlockname=TEST_BGM;

What do you think?

**Comment by MakinoharaShoko** [comment]
这确实是一个好办法

**Comment by labiker** [comment]
Perhaps you can try to shorten the length of the parameter, which can improve the developer's writing experience.
It is ideal to have less than six digits.
For example:
```
changeBg:bg.png -unlock=TEST_CG;
bgm:s_Title.mp3 -unlock=TEST_BGM;
```

パラメータの長さを短くしてみたらどうかなw
スクリプトも書きやすくなれるかもしれません。
たとえば、上のように、6 桁未満にしたらもっといいと思います！

**Comment by MakinoharaShoko** [comment]
> Perhaps you can try to shorten the length of the parameter, which can improve the developer's writing experience.也许你可以尝试缩短参数的长度，这样可以提升开发者的编写体验。 It is ideal to have less than six digits.最好不要超过六位数。 For example: 例如：
> 
> ```
> changeBg:bg.png -unlock=TEST_CG;
> bgm:s_Title.mp3 -unlock=TEST_BGM;
> ```
> 
> パラメータの長さを短くしてみたらどうかなw 如果把参数的长度缩短一下，会怎么样呢w スクリプトも書きやすくなれるかもしれません。 也许这样写脚本会更容易。 たとえば、上のように、6 桁未満にしたらもっといいと思います！例如，就像上面那样，我认为如果能少于6位数就更好了！

Indeed, the length of the parameters has been reduced, but the meaning has also become less clear

**Comment by generalfreed** [comment]
@MakinoharaShoko @labiker 
Thank you.
I will consider implementing it with "-unlockname".

**Comment by generalfreed** [comment]
Complete.
