### ISSUE TITLE
Suggestion for the "textbox" (「文本框」建议)

### ISSUE THREAD

**Issue by IdrilK** [MakinoharaShoko/WebGAL#342]
[ -r == | ] Ok release 4.4.3 => 
```
« -r » for add at a new line :
Me:Blablabla -r -notend;
:an other line, Blablabla -concat;


「-r」用于添加新行：
我：Blablabla -r -notend;
：另一行，Blablabla -concat;
```

_________

For intro and text:
-w:1000 (wait milliseconde)
-wi (wait click or spacebar)
-wi:x (wait input a letter ;))
-wi:x+y (wait input a letter + an other)

对于介绍和文本
-w:1000（等待毫秒）
-wi（等待点击或空格键）
-wi:x（等待输入一个字母 ;))
-wi:x+y（等待输入一个字母 + 另一个）

___________

An example :
Me:Blablabla -r -w:2000 -notend -next;
:Other line Blablabla -concat;

一个示例：
我：Blablabla -r -w:2000 -notend -next;
：另一行，Blablabla -concat;

**Comment by MakinoharaShoko** [comment]
你可以尝试用 | 来代替换行符，配合 -notent -concat 应该也可以使用，因为我们将 | 替换为换行符

**Comment by MakinoharaShoko** [comment]
You can try using "|" to replace line breaks, and it should also work with the options "-notent -concat", as we are replacing "|" with line breaks

**Comment by IdrilK** [comment]
Yesssss, I just test "|", it's perfect ! 👍 

I saw a "wait" tag mentioned in the discussions for "intro." Will it also work for plain text?

**Comment by MakinoharaShoko** [comment]
I couldn't find any relevant discussions. What does the "wait" tag mean?

**Comment by IdrilK** [comment]
> I couldn't find any relevant discussions. What does the "wait" tag mean?

[Wait Tag Usage in WebGAL]
Oops, The [wait] tag is utilized in Tyrano and Visual Novel Maker. In Ren'Py, it acts as a « pause » tag. So more like here: https://github.com/MakinoharaShoko/WebGAL/issues/348

intro: blabla|blabla -delayTime=3000; introduces a waiting period, pausing.

example with dialogue:
MyName: My text blablabla -delayTime=3000 -Next; - This advances the text after a 3-second delay.

Moreover, consider the option of using "-delayTime=none -Next;". With "none" (distinct from 0), the text awaits either a click or a spacebar press.Alternatively, the syntax "-delayTime -Next;" with no value (0 or none) also results in a pause until a click or spacebar press. This idea could be streamlined by establishing a default value of 0.001 for delayTime.

Additionally, extend this functionality to intro, the option of "wait input" could be employed:
intro: blabla|balbla -delayTime=none;
or
intro: bblabla|blablabkla -delayTime;

**Comment by MakinoharaShoko** [comment]
Okay, I understand what you mean. Implementing the waiting for an event in a script can be quite complex in WebGAL, but I think it's a great suggestion and we will definitely consider it

**Comment by IdrilK** [comment]
and, suggest other variant for this with choose:

choose:Blabla:label1|Blabla2:label2|Blabla3:label3 -delayTime=3000; 

a timer show at screen after this delay si you don't hava click he go to the first choice (or last ?) automatically.

**Comment by MakinoharaShoko** [comment]
Redirect to #374
