### ISSUE TITLE
About 2D Lip Sync and Blink

### ISSUE THREAD

**Issue by generalfreed** [MakinoharaShoko/WebGAL#344]
I tried to implement something like this.
2D lip sync and blink.
Can I have your opinion?

**2D_lip_sync**
https://github.com/MakinoharaShoko/WebGAL/assets/71590526/f9538e34-b59b-461b-8c3d-830f69f30c9b
The following images are required for lip sync
・open mouth
・half-open mouth
・close mouth

**2D_blink**
https://github.com/MakinoharaShoko/WebGAL/assets/71590526/8f637ffe-c3a7-4e99-9eca-26b333063cee
The following images are required for blink
・open eyes
・close eyes

These are done during vocal playback.

**Comment by MakinoharaShoko** [comment]
This feature looks very interesting. I wonder the useage of this feature complex or not
