### ISSUE TITLE
Added animation for Full Screen Text and added to delay time

### ISSUE THREAD

**Issue by generalfreed** [MakinoharaShoko/WebGAL#348]
**The following animations will be added to full screen text**
・fadeIn (default)
https://github.com/MakinoharaShoko/WebGAL/assets/71590526/c495287b-937d-4cfe-8ead-42c516f24f4f

・slide in
https://github.com/MakinoharaShoko/WebGAL/assets/71590526/eb1b3ea1-5055-48d9-acda-1a966283f435

・Typing Effect
https://github.com/MakinoharaShoko/WebGAL/assets/71590526/6e354d44-07d9-4a54-8534-6246a58c937e

・pixelateEffect
https://github.com/MakinoharaShoko/WebGAL/assets/71590526/98c6e712-6f55-4391-b9e2-b8d101c49eac

・reveal Animation
https://github.com/MakinoharaShoko/WebGAL/assets/71590526/214156d2-5b16-4d93-ac84-44d580fb7d84

also add a delay time

**Example script:**
intro:*Added animation to the intro.|It's can also set the delay time. -animation=fadeIn -delayTime=3000;
intro:*Added animation to the intro.|It's can also set the delay time. -animation=slideIn -delayTime=3000;
intro:*Added animation to the intro.|It's can also set the delay time. -animation=typingEffect -delayTime=3000;
intro:*Added animation to the intro.|It's can also set the delay time. -animation=pixelateEffect -delayTime=3000;
intro:*Added animation to the intro.|It's can also set the delay time. -animation=revealAnimation -delayTime=3000;

**Also fix for Trerra**
*Additional image
![image](https://github.com/MakinoharaShoko/WebGAL/assets/71590526/7e40bee6-1acd-4383-88b8-5f1f18cf391b)

**Comment by MakinoharaShoko** [comment]
This feature looks good, with added options for customization. I'm really looking forward to this update

**Comment by generalfreed** [comment]
@MakinoharaShoko
I’m sorry to bother you , but code review please.

**Comment by generalfreed** [comment]
Done
