### ISSUE TITLE
Suggest : @(getVar)

### ISSUE THREAD

**Issue by IdrilK** [MakinoharaShoko/WebGAL#351]
Choose surname for Mathew -next;
choose:Mat:label1|My dear:label2|Eurk !:label3;

label:label1;
setVar:**matname**=Mat;
jumpLabel:more;

label:label2;
setVar:**matname**=My dear;
jumpLabel:more;

label:label3;
setVar:**matname**=Eurk !;

label:more;
Me:blabla blabla blabla,  @matname , blablabla.;
@matname: blabla blabla.;
Me: Non  @matname ;

_____
Similar with
setVar:**mynumber**=8;
...
:My number is @mynumber ;

_____
Need more description ? ^o^

**Comment by MakinoharaShoko** [comment]
The functionality of variable interpolation has been on our agenda for some time now, and it may be implemented in conjunction with obtaining input from the user in the future

**Comment by IdrilK** [comment]
ok, so, I've come up with a solution for individuals who want to utilize call a function "getVar" but without calling "getVar".
__________

__________
```
Choose surname for Mathew -next;
choose:Mat:label1|My dear:label2|Eurk !:label3;

label:label1;
setVar:matname=1;
jumpLabel:more;

label:label2;
setVar:matname=2r;
jumpLabel:more;

label:label3;
setVar:matname=3;

label:more;
Me:blabla blabla blabla, -notend; 
callScene:Varmatname.txt;
, blablabla. -concat;

callScene: matname.txt;
:blabla blabla -concat.;

Me: No,  -notend; 
callScene:Varmatname.txt;
```

__________
_file matname.txt_

```
Mat: -notend -when=brodyName==1;
My dear: -notend -when=brodyName==2;
Eurk !: -notend -when=brodyName==3;
```

__________
_file Varmatname.txt_

```
Mat: -notend -concat -when=brodyName==1;
My dear: -notend -when=brodyName==2;
Eurk !: -notend -concat -when=brodyName==3;
```
