### ISSUE TITLE
Character Voice not playing in Edge and Chrome（ブラウザでキャラクターの音声が再生されない）

### ISSUE THREAD

**Issue by generalfreed** [MakinoharaShoko/WebGAL#387]
I deployed a game I developed with WebGAL on the [render](https://www.render.com/) service. However, I'm facing an issue where the character's voice does not play in certain browsers.

**URL to Reproduce:**
https://digigame-webgal.onrender.com/

**Browsers affected:**

Microsoft Edge (version: 117.0.2045.60)
Google Chrome (version: 117.0.5938.150)

**Browsers not affected:**

Firefox (version: 118.0.2)

This issue hinders the gaming experience for users on these browsers. Could someone look into this?

**English:**
I encountered an issue where the character voices are not being played on specific browsers after deploying my WebGAL game on the render service. The game runs without problems on Firefox, but the voice doesn't play on Edge and Chrome.

**中文:**
我在render服务上部署了我使用WebGAL开发的游戏后，遇到了角色语音在特定浏览器上无法播放的问题。游戏在Firefox上运行没有问题，但在Edge和Chrome上声音不播放。

**日本語:**
私はWebGALで開発したゲームをrenderサービスにデプロイした後、特定のブラウザでキャラクターの音声が再生されない問題に遭遇しました。 Firefoxでは問題なくゲームが実行されますが、EdgeとChromeでは音声が再生されません。

![image](https://github.com/MakinoharaShoko/WebGAL/assets/71590526/a27cfb16-27ef-4ce9-9809-f27c941ecafe)

**Comment by MakinoharaShoko** [comment]
Try using purely English and numerical names for audio files

**Comment by generalfreed** [comment]
> Try using purely English and numerical names for audio files
The voice is now played successfully.
https://digigame-webgal.onrender.com/

Thank you.
