### ISSUE TITLE
打算做语音在下一个语音之前不中断么？

### ISSUE THREAD

**Issue by Robert2333** [MakinoharaShoko/WebGAL#406]
暂时没这个计划的话，我最近可以做下，提个pr

**Comment by MakinoharaShoko** [comment]
你好，感谢你对 WebGAL 项目的关注！
刚刚看了一下，目前的实现是：遇到新的对话（无论有没有语音）就中断，但是非对话命令不中断。
可能我之前想的是，遇到对话就中断是为了防止没有语音的人物错误地被记录了语音的存档（因为语音是状态，在存档的时候会被记录），也没什么好的办法解决（语音在播放的时候总是存在状态表中）
如果你想到了好的办法，并且能避免语音在存档时被记录，可以尝试一下！

**Comment by Robert2333** [comment]
这样有个很尴尬的点在于如果“第一视角”没有语音的话，它还是会中断   (lll￢ω￢)

**Comment by MakinoharaShoko** [comment]
是的，我已经发现了，要改善这个问题，可能要改变语音的播放机制

**Comment by Robert2333** [comment]
> 是的，我已经发现了，要改善这个问题，可能要改变语音的播放机制

话说铁子你中断代码是写在哪里了。代码有点多，我还只找到了你播放的那块代码。

**Comment by MakinoharaShoko** [comment]
https://github.com/MakinoharaShoko/WebGAL/blob/ddc209e68d7e100dc059e8bb200aa805bf6ae33d/packages/webgal/src/Core/gameScripts/say.ts#L40-L41

**Comment by Robert2333** [comment]
![QQ截图20231123223903](https://github.com/MakinoharaShoko/WebGAL/assets/16183411/bd113056-a39a-47c8-a002-a385bb4a717f)
铁子，我感觉这么简单处理下是不是就可以了，还是别的地方会出问题。在没有语音的对话里面，没有对应的“语音文件参数“的，如果为空的话，继续就行了。

ps：如果可以的话，得加个整体开关【是否中断语音】

**Comment by Robert2333** [comment]
> 这样处理会导致存档的时候把上一句的语音存进去。游戏中可能没问题，但是读档的时候会发现，一个没有语音的人物在说语音

我尝试了下，好像不会出现这个问题。

**Comment by MakinoharaShoko** [comment]
那你可以先提交 pr，之后我测试

**Comment by Robert2333** [comment]
> 那你可以先提交 pr，之后我测试

我周末加个全局开关再提交吧。

**Comment by MakinoharaShoko** [comment]
好
