### ISSUE TITLE
多行文本渲染，疑似bug

### ISSUE THREAD

**Issue by SoneMiyuki** [MakinoharaShoko/WebGAL#413]
三行文本在浏览器里只渲染出两行

`
:web1|web2|web3 -fontSize=default;
`

**Comment by SoneMiyuki** [comment]
版本是基于WebGAL 4.4.7的包

**Comment by MakinoharaShoko** [comment]
新版本为文本行数加了限制，在大号和中号字体下显示 2 行，小号字体下显示 3 行

**Comment by MakinoharaShoko** [comment]
![Screenshot_20231205_094352_Chrome](https://github.com/MakinoharaShoko/WebGAL/assets/30483415/b1de67e9-7256-4e70-8480-b1c4f6446b0e)
