### ISSUE TITLE
NVL.

### ISSUE THREAD

**Issue by ishani-rgb** [MakinoharaShoko/WebGAL#47]
（使用谷歌翻译，抱歉！）

是否在考虑 NVL 模式？和INTRO差不多，所以不知道实现起来会不会有问题？

你已经完成的工作是惊人的！谢谢！

**Comment by MakinoharaShoko** [comment]
我们会在以后的开发中考虑加入nvl模式。

**Comment by MakinoharaShoko** [comment]
Moved to #388
