### ISSUE TITLE
友商又多了一个！

### ISSUE THREAD

**Issue by RimoChan** [MakinoharaShoko/WebGAL#54]
![](https://user-images.githubusercontent.com/20064807/138563878-5e5e7863-3864-47d3-a35a-bcff0ee7139f.png)

**Comment by 2439905184** [comment]
大师球 @RimoChan

**Comment by RimoChan** [comment]
> 大师球 @RimoChan

太大了，不行！

**Comment by 2439905184** [comment]
各位对我的资料库感兴趣吗，收集了各种gal引擎和冷门引擎官网和相关网站
https://github.com/2439905184/Galgame-Engine-Collect

**Comment by RimoChan** [comment]
> 各位对我的资料库感兴趣吗，收集了各种gal引擎和冷门引擎官网和相关网站 https://github.com/2439905184/Galgame-Engine-Collect
干你怎么不写Librian，居然背叛我们！

**Comment by sb-child** [comment]
> 各位对我的资料库感兴趣吗，收集了各种gal引擎和冷门引擎官网和相关网站 [2439905184/Galgame-Engine-Collect](https://github.com/2439905184/Galgame-Engine-Collect)

妳竟然没有把 Librian 加进去, 妳太坏了!

**Comment by 2439905184** [comment]
没想到 忘了，我看过Librian的官网

**Comment by 2439905184** [comment]
Librian已加入资料库 求原谅
