### ISSUE TITLE
有考虑上 TypeScript 吗？

### ISSUE THREAD

**Issue by lixiang810** [MakinoharaShoko/WebGAL#87]
方便维护和重构。如果这个项目现在没有别的事项，我可以 PR 一个用了 TypeScript 的版本过来。

**Comment by MakinoharaShoko** [comment]
我本来是有重构计划的，但是主要工作内容是优化项目结构和把底层换成webgl，用typescript倒是没想过（主要是因为暂时没发现哪个模块特别需要做静态类型检查）。
现在简要和你说明一下当前的情况吧：
1、我计划将演出的渲染换成webgl，这样可以支持更丰富的效果。
2、将UI层和舞台（演出）分开，UI继续用react，做响应式布局，方便跨平台。
3、进一步解耦，让各模块各司其职。

但是现在有个最大的问题：
本人今年要准备硕士研究生入学考试，以上重构都要在2023年才能逐步提上日程（逃
如果你有重构计划，我可以单独开一个分支以供pr，但是由于明年开始这个引擎会大改，所以......

**Comment by lixiang810** [comment]
巧了，我2023年要准备考研（
