### ISSUE TITLE
希望能够适配移动端

### ISSUE THREAD

**Issue by manakanemu** [MakinoharaShoko/WebGAL#9]
现在跨平台的语言有很多，Gal引擎也有不少，真正能发挥Web的优势应该是PC/移动端的跨平台，我试了下，貌似目前没有适配移动端UI，希望开发者能够适配下移动端。

下面是个人想法：这款开发引擎的应用场景是什么呢？是帮助Gal开发者将文本、图像、音频打包成网页，方便分发？还是在服务端直接搭建，用户直接远程访问？如果是前者不用考虑懒加载问题，如果是后者，那可能还需要考虑一下，这个引擎服务的是免费Gal还是收费Gal。免费Gal无需多言，收费Gal可能还需要考虑下资源加密问题，比如音频用ts序列加密下。图像用临时token等等。

**Comment by MakinoharaShoko** [comment]
移动端适配一直是该引擎工作的一个重点，只是目前我正在着力于添加功能，所以暂时还没有开始正式适配。至于付费gal所面临的加密问题，由于我的图片和音频都是实时请求的，有经验的开发人员只要稍加修改，再配合后端，就能得到一个可靠的加密传输方法。作为一个纯前端项目，这个问题暂时不是我需要考虑的。
